### ISSUE TITLE
difficulty in searching admin section 

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#102]
This is the same as we spoke about a few weeks ago Ella - it is a real challenge to find the stories that you want to put in promo blocks or related content - the search seems to do nothing - even when it is the correct title, and it takes ages to search through all the listings - it really is an issue.  The text below is from Rob - sent this morning:
Hi.  Not sure if this is a glitch, my incompetence, or whatever, but I wanted to note something that is a bit of a pain on the new site.  Let's say I want to change a story in the promo block for the featured news stories.  I go into edit page and then I have a box on the left with every blog we ever did in alphabetical order, and a box on the right in which to add the ones we want to feature.  

Finding a story is very tricky.  If I put in some words to narrow the search, it doesn't seem to do anything.  If I try to scroll down, it does so in blocks of 20 or so, refreshing each time before adding the next 20.  But sometimes it just hangs.  I just tried to put the latest blog, 'Invest in the Future'.. put that in as a search, nothing, so scrolled down, got to G, and it hung there.  Could be my computer, but it's a real pain finding the actual story you want to put in the right hand box.  Any tips? 

Can you please look into a better way to make this work - it is adding significantly to our workload in practice.

Cheers

**Comment by arhinostorm** [comment]
A large part of this is do to the amount of content. For instance you have
around 1800 blog posts. The computer can only filter that information so
quickly. A way to speed things up is to be more strict about what you can
select. Related content currently lets you add anything, blogs, stories,
pages, whatever - but that comes at a cost. If you took at blogs from that
list of related content you'd speed it up considerably.

Another option is to get rid of or at least archive old content. That's
what slows it down.

**Comment by yvonnestruthers** [comment]
Hi Ainslie - Let me know what you think re the above - potentially archiving old content sounds like a good possible option (if the archive were then removed from the items which return in the related content search)

In the mean time, searching for one more unusual word in the title really helps - for example - looking for this article: https://transitionnetwork.org/news-and-blog/can-funders-systems-change-learning-supporting-new-economy/

I tried searching system change, which does return it, but there is a lot of other content from the possible list (because these words or whole term is in a lot of content). Where as, if I search for 'funders' it appears near the top. 

I did the same thing with a few other examples too and searching that way brought up what I wanted very near the top of the list. 

I hope that helps, and let me know how you'd like to proceed with the archiving option.

**Comment by thisisyoke** [comment]
@ainsliebeattie did the above advice help out? Let me know if you want us to take any further action on this

**Comment by ainsliebeattie** [comment]
Sorry - this is a real challenge for us - we don't want to take down old information as it is key to some of our audience and provides a really valuable archive for them. We therefore would like you to think through any other alternative that might work. Perhaps we can talk about this in our next catchup.
