### ISSUE TITLE
moving frame of hero image

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#11]
Hi...the hero image in the blogs seems to have moved up and the excerpts are not looking correct. This could be due to the lack of photo, but none the less it looks strange.  I am going to put it as urgent but I appreciate that it is the first thing I have looked at tonight and it may be that there is already a fix or a log of this issue.

example here: http://transitionmovement.org/news-and-blog/when-loorbach-met-hopkins-on-transition-and-research/

Also two screenshots:
<img width="1175" alt="screen shot 2016-09-29 at 9 49 25 pm" src="https://cloud.githubusercontent.com/assets/22507393/18971869/a4ad88dc-868e-11e6-8c19-4618c34b9d51.png">
<img width="1255" alt="screen shot 2016-09-29 at 9 48 58 pm" src="https://cloud.githubusercontent.com/assets/22507393/18971872/a91ce674-868e-11e6-88e2-8eeafd6ef4ef.png">

cheers

**Comment by yvonnestruthers** [comment]
@arhinostorm please can you feedback/address?

**Comment by arhinostorm** [comment]
In the options page we've added an extra field called 'news image'. This is the default image that appears as hero's and thumbnails for all news items that don't have their own image set.

The reason you're seeing the empty hero box and the missing images on the news page is just because this wasn't set. I've set it now with a champagne image. Obviously feel free to change it to something more fitting in the options page.

Before this latest update, the news images were using the field 'default thumb' field in options. This is still used, but it's used for pages that appear on landing pages e.g. http://transitionmovement.org/about-the-movement/what-is-transition/. 

We've just added this extra field so there is a bit more variety on the site. You can pick an image for news that is suitable 'newsy' and one for hubs and initiatives that suits, then a generally fallback one for pages.
