### ISSUE TITLE
Culture section

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#12]
Hi - I am trying to upload new content and I have added a text box in the flexible content - but I cannot add any text - I can see that maybe something is being entered but I cannot see it on my screen - the text box remains empty.  This is urgent...I must be doing something fairly stupid...but I I managed to update the snippet without any issue...can you help first thing Wed morning please!

**Comment by yvonnestruthers** [comment]
Hi Ainslie - this is an odd one, as the text boxes had been working previously - I have replicated the issue my end though so something must have had a knock on effect for this to occur. 

I've contacted Tom to fix it but have found a work around in the mean time so that you can continue to add content. I've done a test on the page so that you can see but if you add a text box, then click update you'll then be able to go back to the text field you created and type the text. 

http://transitionmovement.org/about-the-movement/the-charity/culture/

@arhinostorm please could you address this - it's only the text flexible content field that seems to be affected (i added a quote and that worked fine). Currently you cannot type text when you add a repeatable text field. You must click update and then you can type the text in.

**Comment by arhinostorm** [comment]
This was a problem with the plugin itself (advanced custom fields). Thankfully this is possibly the most used wordpress plugin and the developers are always on the case. They just released an update which addressed this issue, which I just applied.

**Comment by ainsliebeattie** [comment]
thanks for the fix guys...off to start uploading!

Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb
