### ISSUE TITLE
Embed code on http://transitionmovement.org/do-transition/training/trainings/

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#25]
Hi all

I spotted that on this page: http://transitionmovement.org/do-transition/training/trainings/ The Youtube link appears as a URL rather than as an embedded video.

It appears correctly on the source page http://transitionmovement.org/do-transition/training/trainings/thrive-training/

Could you take a look.

Thanks

Sam

**Comment by samuk** [comment]
Actually checking here: http://5ufovq.axshare.com/#g=1&p=courses&c=1 it seems that the content from Thrive shouldn't be appearing here at all. I'll see if we've just inputted it incorrectly somehow.

**Comment by thisisyoke** [comment]
For youtube embed, only ever copy and paste the URL, not the embed code. Just paste the url into the text area and it will convert it to a video automatically

**Comment by samuk** [comment]
Hi Ella, OK will do.

The Youtube has been entered with just the URL here: http://transitionmovement.org/wp-admin/post.php?post=365&action=edit

I'm a bit unclear as to whether the full Thrive content should be appearing here at all: http://transitionmovement.org/do-transition/training/trainings/ 

Looking at the wireframe it looks like it should just be the teasers: http://5ufovq.axshare.com/#g=1&p=courses&c=1

Have we entered it incorrectly somehow? Or is there a glitch here?

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

That's correct, the requirement for that section (which is reflected in the wireframe) was only for a short, plain text paragraph therefore this field is built as a plain text field (which is why the YouTube embed will not work here as the field is only for one set style of text). 

It seems like you are adding in quite a bit of information into the Thrive section where it should only be a teaser. As the original requirement was for a teaser only, there isn't currently a page to put that additional information (with the bullets, youtube links etc). 

We could add a 'Read more' to the excerpt, and add another page which would be a child of trainings (using the basic page template) to hold that additional detail, but this would be a change request. It's a simple thing to do and would probably take about an hour. You would then have the option for all Trainings to build the page with all the detail, and then the excerpt would appear in the list view. 

Let me know if that's something you'd like to do and I will raise a change request for you.

**Comment by samuk** [comment]
Hi Ella

I think it may just a bit of user error on our part. 

I've now spotted that we should have been creating 'training types' then creating trainings as children of this.  I'm still not quite clear how we set the 'trainings' to be children of the 'training type' for example;

In my test one: http://transitionmovement.org/wp-admin/post.php?post=7274&action=edit I have selected 'Thrive' check box on the right.

And it appears here:
http://transitionmovement.org/wp-admin/edit.php?post_type=trainings&trainingtype=thrive

But it's not yet appearing on this page: http://transitionmovement.org/do-transition/training/trainings/  
Is there a step I'm missing here?

Also the layout seems slightly out on the 'trainings' pages eg here: http://transitionmovement.org/do-transition/training/trainings/thrive-training/ with the Date/ Location too far over to the left.

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

We need to have each thing as a seperate issue so that it's clear for the developer what needs to be addressed, so I'm just going to close this one and raise 2 new ones for the queries in the comment above, and I'll come back to you via those threads.
