### ISSUE TITLE
Clickable links in FAQ section?

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#27]
I noticed that Mike has put links in his FAQ here: http://transitionmovement.org/do-transition/starting-transition/how-to-start/ 

I'm unable to click the link unless I right click > New tab.

Is there a way to resolve this?

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

I've just tested this and can click on the links as normal so I'm not sure why you would need to be right clicking. Is it that you want the link to open in a new tab automatically rather than using your current window? (If so you can do this in the settings when you add the link into the text). 

Thanks

Ella

**Comment by samuk** [comment]
Hi Ella

When I click on the link using Chrome (Version 47.0.2526.80 (64-bit) the FAQ item closes, rather than the link opening.

**Comment by yvonnestruthers** [comment]
Hey Sam,

I think you may need to update your Chrome, as you are quite a few versions behind - I am on version 53.0.2785.143 (64-bit) 

Thanks

Ella

**Comment by samuk** [comment]
Hi Ella 

Yep fair point!  I've just updated to 53.0.2785.143 but the issue is persisting.

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Thanks for letting me know - any ideas @thisisyoke ?

**Comment by yvonnestruthers** [comment]
Hey @arhinostorm please could you advise on this one whilst you're working through the other issues as well?

**Comment by arhinostorm** [comment]
Javascript issue where any click inside of FAQ item triggered close. Have fixed.
