### ISSUE TITLE
Adding a category to People page

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#32]
Can we add a category for the people page that says Transitioners and automatically uploads to the meet the transitioners page?

Given that Transitioners we upload will always go onto the Meet the Transitioners page, it would be really helpful to have a category that we could click when uploading so that it just goes straight in there as we go.

**Comment by yvonnestruthers** [comment]
I'm not sure about this one - it sounds like it could be technically quite complicated to administer @thisisyoke what are your thoughts?

**Comment by thisisyoke** [comment]
This could be done, but it would mean some development amends to the people template to be slightly bespoke for the Transitioners template. This would also mean you wouldn't be able to manually add people to the page as it has to be one way (manually) or the other(automatic), not both. 

This could become a little confusing to remove a person from the Meet the transitioners page , you would have to find who they are, then go and edit the person and uncheck the box, rather than just removing them from the list on the actual meet the transitioners page.

Up to you I guess, it might not be as useful once your initial content adding is done as well... would the development work make it worthwhile in the long run? If you want an estimate we could do so happily.

**Comment by yvonnestruthers** [comment]
@ainsliebeattie please see Jay's comment below and let us know how you'd like to proceed. Thanks!

**Comment by thisisyoke** [comment]
@ainsliebeattie if you could add your updated thoughts here and we can estimate if needed

**Comment by ainsliebeattie** [comment]
I am going to park this one as not a top priority for now.  Cheers.
