### ISSUE TITLE
Bullets in text

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#34]
the bullets throughout the site do not seem to be indenting, or where they do indent it does not look like enough of difference.  Can we fix this to really make it clear what we are highlighting with bullets?  I have added a couple of screenshots as examples and links to those pages. 
http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/healthy-groups/
http://transitionmovement.org/about-the-movement/what-is-transition/
<img width="922" alt="screen shot 2016-10-20 at 11 36 36 am" src="https://cloud.githubusercontent.com/assets/22507393/19556538/851344cc-96b9-11e6-9510-8dc76c0dc6ca.png">
<img width="1240" alt="screen shot 2016-10-20 at 11 36 14 am" src="https://cloud.githubusercontent.com/assets/22507393/19556558/996a348a-96b9-11e6-8404-62586c964b5f.png">

Note that the what is transition page - principles list is about to change so it might not be there when you go back in - it will have it's own page as a child of about the movement - but I haven't done it yet. problem will still remain.

**Comment by yvonnestruthers** [comment]
Hey @ainsliebeattie we wouldn't normally treat this one as urgent as it's not a technical issue that's wrong so it would normally go into the 'not urgent' category, but I know it was important to you that it's sorted so we will do it on this occasion. 

@arhinostorm please could you make it so bullet points and numbered lists indent so that the bullet/number starts where the indented sentence currently begins in the bullet list. If you need clarification let me know - may be easier to explain over the phone!
