### ISSUE TITLE
Can't add hyperlinks in FAQ boxes

### ISSUE THREAD

**Issue by MikeTransition** [transitionnetwork/TNv3.0#4]
I have tried adding hyperlinks in the faq boxes but cant do that, pretty essential that we can do this as we will be adding links to resources in there.

**Comment by yvonnestruthers** [comment]
Hi Mike,

Please could you give me a link to where you're trying to add the link so I can take a look? 

Thanks

**Comment by MikeTransition** [comment]
http://transitionmovement.org/do-transition/starting-transition/how-to-start/ in the FAQ boxes at the bottom of the page

**Comment by yvonnestruthers** [comment]
@thisisyoke can you comment on this one please? I can see from the CMS that the area above FAQs has been designed as the template for adding relevant resources, and then in the FAQ section the formatting is fixed to text only. Can you comment on design history for this, and complexity of adding hyperlink capability (if not at odds with a previous design decision).

**Comment by yvonnestruthers** [comment]
Hi Mike,

Tom has fixed this, but due to this being a repeatable field within a flexible content field there are a few steps. Instructions as follows: 

1) edit the page where you want an FAQ section - I have done an example here - http://transitionmovement.org/do-transition/reconomy/
2) click the 'add row’ button under ‘flexible content’ section on the edit page
3) select ‘FAQS'
4) Click ‘add row’ button next to faq item and it will create the first FAQ item for you - give it a title and a question
5) At this stage you'll notice you can't type an answer
6) Click 'update'which will reload the page
7) Answer field will now be rich text so you can add the links in there
