### ISSUE TITLE
Culture page not working correctly

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#41]
The Photo and italics of quote not working on the culture page - see screenshots: 
<img width="872" alt="screen shot 2016-10-21 at 11 20 07 am" src="https://cloud.githubusercontent.com/assets/22507393/19636671/a77e717e-99c2-11e6-95b3-b76aecdd4343.png">

there is also an extra line between boxes 2 and 3 in text.
<img width="899" alt="screen shot 2016-10-21 at 11 21 20 am" src="https://cloud.githubusercontent.com/assets/22507393/19636716/0446b89e-99c3-11e6-8875-e0a9343cfd7c.png">

**Comment by yvonnestruthers** [comment]
Hi @ainsliebeattie can you clarify what isn't working about the photo as I'm not sure? 

@arhinostorm for some reason the italics weren't pulling through but I've just put them in and re published the page so they are all in there now so that one is sorted. Looks like there may be a bit of extra padding between boxes 2 and 3?

**Comment by yvonnestruthers** [comment]
Re the padding between boxes 2 and 3 - this is because each text box has 40px space top and bottom. You have 2 text boxes together here, hence the extra space. To rectify this, you need to just continue the text in the same text box and break with a paragraph break to give you the same space. 

Please feed back on the photo comment, as we are not sure about that one at the moment. Thanks!

**Comment by yvonnestruthers** [comment]
Closing this issue as the queries have been addressed
