### ISSUE TITLE
Mapping page

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#43]
Wehn you click on afghanistan in the mapping you get repair cafe pasedena. Can't see why this is but afghanistan constantly produces strange search results.
We haven't been through all the countries but clearly the search results are not picking up the correct constraints.

**Comment by yvonnestruthers** [comment]
Sorry but I cannot replicate this issue. It does sound like a data issue, rather than anything wrong with how the map has been implemented. I clicked on afghanistan and it recognised it as Afghanisatan. I also tried typing various Afghan cities into the search bar in the map and it found them OK. I've also tried testing with various other cities and UK post codes which all worked fine. 

We've discussed in the past that the map is not completely 'fool proof' which is why we added in the moderation stage for initiatives to ensure the results are as accurate as possible. If it doesn't find the intended location straight off, you can simply move the pin to the desired location manually, or try another search term. 

An example of this is if you type 'spike island' (Yoke location) it gives you somewhere in long island, which obviously isn't correct so I typed the next part of the address which is Cumberland Road - but there are also lots of Cumberland Roads, so I typed Cumberland Road, Bristol and that worked. 

I'm going to close this issue for now, as the map does seem to be working properly. It is the case that the pin may not be 100% accurate in less 'well mapped' areas of the world, which is why Tom implemented the option to drag the pin manually as well so that you have the option to be as accurate as possible.
