### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#46]
When we agreed on the healthcheck we talked through having a process when all seven scores should be inputable through the system and would be linked to the initiatives record. This was because we couldn't implement a fully functioning healthcheck in this iteration, but Yoke did say that we would be able to have a very basic input functionality.  There shoud be 7 scores between 1-5 in a form and these should reflect back in the initiative record. How do we get this done now?

**Comment by yvonnestruthers** [comment]
I've had a look back at the scope for this in the PID which was as follows: "The health check will be a simple form using Gravity Forms. Any more complex quizzing or scoring could be available via additional Gravity Form plug-ins but these would not be included as part of this project."

Jay showed Sam how to set up a form for the healthcheck page as part of the training so I believe he is implementing this. This will only be using the basic form elements of gravity forms (as per the PID). There is nothing scoped out at this stage to have this connected to an initiative record, so we would recommend that you have a field in the form for people to input what their initiative is so that you can track this back manually for the moment. We can then scope something more sophisticated in phase 2 if required.

**Comment by yvonnestruthers** [comment]
Hi @ainsliebeattie and @samuk 

I'm just checking through the repo for issues that can be closed, and noticed that the form has not yet been implemented for the Healthcheck, following my comment above. I just wanted to double check this is on your radar for this week. 

I also just happened to notice that a file hasn't been uploaded to this page, so that when you click on the 'download resource' link, nothing happens: 

http://transitionmovement.org/resources/health-check/

Please can you action this and then close this issue when done? 

Thanks!

**Comment by thisisyoke** [comment]
Is there an update on this one @ainsliebeattie or @samuk ?

Another option is to go for the quiz option and install this add on for gravity forms:

http://www.gravityforms.com/add-ons/quiz/

This would extend the forms plugin to allow you to create a quiz, with multiple choice answers with scores associated with these. You could then show a results page once the quiz has been taken. 

Maybe if this is of interest you could add in here the details of how you see it working, or how you would like to deliver the form, and we will see if we can bend this add on to meet your needs.

**Comment by ainsliebeattie** [comment]
Hmm - I too thought this was done. @samuk  - were we not talking about this functionality working last week. If it is not and you need some support, I am happy to get a costing from Jay to make it happen as we really need it up there and if you are flat out, then we need to get support externally.  Jay - perhaps you can check in with Sam this week and see if it might be appropriate to work out a cost to do this if you are able.

**Comment by samuk** [comment]
This has been resolved
