### ISSUE TITLE
Only events appear in upcoming courses and events section on homepage

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#48]
We agreed that we would have  a training calendar on the home page, not just a listing.  How can we make this functionality work?
<img width="1250" alt="screen shot 2016-10-24 at 8 38 27 am" src="https://cloud.githubusercontent.com/assets/22507393/19637125/512da63e-99c5-11e6-9787-3e3714f16fdd.png">

**Comment by yvonnestruthers** [comment]
I've checked back in the PID, and there isn't anything about a training calendar in the scope, so this isn't something that has been estimated for/included in this phase of the project. 

Could you list out the requirements for this please, and then I can estimate for it as something to be added in to the requirements of phase 2.

**Comment by yvonnestruthers** [comment]
Following up after call with Ainslie:

The format we have currently is as agreed, so we will proceed with this layout for now. 

However currently only events are being pulled into the list, when TN would like it to be both events and trainings showing. 
- list currently automatically pulls any upcoming events (no selection process) 
- to prevent box being empty, past events will show if there are no new ones to replace them 

There are 2 options for the addition of trainings to this list: 
1) we enable trainings to be listed in the same way as events (ie by date). For this option there wouldn't be a selection process, it would just be the closest upcoming events from the present date
2) if TN need control over which events show, we could add another area to select the courses to show in the homepage editor instead of being automatically pulled by date

For both of these options we will need to have seperate columns - 1 for events and 1 for trainings 

@ainsliebeattie please could you confirm which of the above approaches you'd like to take? We will then estimate the time needed. 

Thanks!

**Comment by yvonnestruthers** [comment]
Another thing on here whilst we are doingthis work - 'courses' needs to change to 'trainings' in the title

**Comment by yvonnestruthers** [comment]
Confirmed requirements for this are as follows: 
- create 2 columns within the upcoming courses and events box on the homepage - 1 for trainings 1 for events
- ability to select the trainings and events which appear on the home page via a tick box in the event/training input pages
- trainings and events not pulling automatically by date
- amend the way events is currently working to allow TN to select events they want to appear on home page
- Out of date trainings and events should not appear
- if there are no trainings or events to show - display the following text: Let us know if you are organising a Transition training/event to be listed here. Email us on websupport@transitionnetwork.org

**Comment by yvonnestruthers** [comment]
Just adding reference points to this issue so it's all in one place: 
- Tom recommended that it is much more user friendly from a management point of view if the selection process for the trainings and events to appear on the homepage is the same as selecting other items to appear on the homepage
- therefore rather than a tick box in the event page itself, Tom has added a selection section in the homepage editing area for these to be seleted http://transitionmovement.org/wp-admin/post.php?post=98&action=edit
- only upcoming trainings and events will appear in the list to be selected
- once a training or event goes out of date, it will no longer show in the homepage or in the selection list
