### ISSUE TITLE
REconomy page missing

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#51]
When you click on REconomy under do transition it takes you this page:
<img width="1014" alt="screen shot 2016-10-24 at 8 44 18 am" src="https://cloud.githubusercontent.com/assets/22507393/19637291/26d14430-99c6-11e6-8431-35c1e5cef446.png">

**Comment by arhinostorm** [comment]
You have two pages called reconomy. The main menu grabs the items and it getting confused because you now have two reconomy pages. Are both needed? 

The easiest fix is to rename this page:

http://transitionmovement.org/wp-admin/post.php?post=7879&action=edit

So it is not called reconomy.

**Comment by yvonnestruthers** [comment]
@ainsliebeattie @samuk please could you action Tom's feedback to rename the post he has specified, which will prevent the clash of page names? Thanks

**Comment by yvonnestruthers** [comment]
Hi @ainsliebeattie and @samuk 

Just checking this one is on your list for this week - I'm just clearing through and closing issues on the repo which have been addressed and noticed Tom's feedback above has not yet been implemented. 

Please can you implement and then close this issue once done? 

Thanks

**Comment by yvonnestruthers** [comment]
Update:

There are reconomy pages in the About the movement and the Do transition sections of the site. 

Reconomy page in About the movement works fine, but when you select Reconomy under the do transition section, you get sent to the http://transitionmovement.org/about-the-movement/what-is-transition/reconomy/  page

**Comment by ainsliebeattie** [comment]
Just checking..is this to tom or to me..do I need to do anything...how do I
redirect to the page I built.

**Comment by yvonnestruthers** [comment]
Hi Ainslie,

Sorry this is for Tom, not you :) 

Tom is trying to get to the bottom of this (he can't replicate this on his local).

**Comment by yvonnestruthers** [comment]
This is now fixed. Background is: 

http://wordpress.stackexchange.com/questions/182424/can-i-have-two-child-pages-of-different-parents-with-the-same-name

Reconomy is a parent of pages - eg http://transitionmovement.org/about-the-movement/what-is-transition/reconomy/reconomy-around-the-world/

http://transitionmovement.org/about-the-movement/what-is-transition/reconomy/what-is-reconomy/

so that means that 'reconomy' is reserved as a slug for those pages, and you cannot have another page with the name reconomy because it tries to use the same slug, and then finds the parent page (which is what was happening). 

so, we have changed the slug for reconomy under do transition to be 'do-reconomy' - this changes the slug in the URL but not the name of the page, so that the clash is prevented and the right pages are found from the relevant parts of the menu
