### ISSUE TITLE
FAQ full width on /healthy-groups

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#54]
On this page
http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/healthy-groups/
http://transitionmovement.org/wp-admin/post.php?post=671&action=edit

The FAQ appears full width. On all other pages it's narrower

eg
http://transitionmovement.org/do-transition/starting-transition/7-essential-ingredients/vision/
http://transitionmovement.org/wp-admin/post.php?post=678&action=edit

Could you take a look? 

Thanks

Sam

**Comment by yvonnestruthers** [comment]
I think this needs to be constrained to the same column width as the rest of the content please @arhinostorm

**Comment by arhinostorm** [comment]
This was caused by there being an resources block on http://transitionmovement.org/wp-admin/post.php?post=671&action=edit that was actually empty. I've put in a check for an empty resource block (obviously a bit of an edge case and unlikely to happen, but still it did here!). The code now doesn't do something weird when an empty block is used - it was that slight bug in code that cause FAQs to be full width (not because they are FAQs, just because anything that proceeded the empty resources block was affected).
