### ISSUE TITLE
10 second load on http://transitionmovement.org/transition-near-me/

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#56]
Hi the load time on http://transitionmovement.org/transition-near-me/ is very long.

I understand it needs to get a lot of data, but from a User point of view it's obviously not ideal.

When I raised it previously Jay suggested at least adding a loading indicator? I guess maybe this one? https://github.com/ebrelsford/Leaflet.loading/blob/master/README.md

 What can we do to improve this?

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

Yes that's fine - we will add this in. Tom please could you implement the simple version which sits with the zoom icons as per the link sam has provided above? 

Thanks!

**Comment by arhinostorm** [comment]
The suggested library is for an older version of leaflet (0.6) and we're using version 1, so afraid it's not compatible. I've implemented my own solution which is slightly different, but still looks neat and does the job.

**Comment by samuk** [comment]
Hi Tom, thanks for this, it looks good and is as requested.

One thing that I was wondering is if it would be easy to load the hubs first? And if this would enable them to load faster?

Query1: Load the 15 hubs
Query2: Load the 1300 initiatives?

If it doesn't work like this, or would be complex to implement then do say.

What would be your estimate to do this?

Thanks

Sam

**Comment by arhinostorm** [comment]
I don't think that would really help speed things up at all. The hubs loading is really quick, but it'd lock up the map when it was processing the initiative pins anyway. So you'd be left with the same problem - which is you can't really use the map until it's all loaded.

**Comment by samuk** [comment]
OK, that's a shame.

I'm guessing there's no way to cache this page? Or is there?

Thanks

Sam

**Comment by arhinostorm** [comment]
The main bottle neck is we need to grab all the initiatives and hubs from wordpress using the get_posts API. That's what takes so long. That generates a json file, and it has to do it every time because it checks for changes. If the JSON file wasn't generated on the fly it would speed it up a lot - but then it's not linked to the CMS, so new initiatives and hubs wouldn't be automatically added to the map. So if you just had a saved json file somewhere with all your markers you'd save a lot of loading time... that's a bit of a can of worms though as then how do you update it and make sure it's in synch with all the data on your site?

**Comment by yvonnestruthers** [comment]
Sounds like a big can of worms to me, and potentially very time consuming so I'd recommend this is best left as is - now that Tom has implemented the 'loading' animation it is clear for the user that the results are coming. 

Are you happy to leave this one as is now Sam?

**Comment by samuk** [comment]
Hi Ella

If there is a relatively simple solution it would be good to improve this page load time

Would it be possible to simply cache this JSON file for x hours at a time using the webserver cache?

Thanks

Sam

**Comment by arhinostorm** [comment]
Hi Sam,

The JSON file doesn't exist as such, so there is no file to cache. In order to cache it we'd need to write some code that creates a file, caches it and recreates it say once a day or twice or day or whatever which is a fairly complex thing to do. That's the can of worms I'm talking about. 

If there were just a file to cache then it would be more straight forward, but that's not the case unfortunately. I can look into possible solutions, but there isn't an easy win or really obvious simple solution in this case.

**Comment by yvonnestruthers** [comment]
Hi Sam,

Following on from what Tom has said - this would need to be properly scoped and thought through, and that isn't a possibility with the time scales we are working to for go live. I have added this to the possible list of requirements for phase 2 but it's not going to be something we can cover as part of this project. 

As the page is working as scoped and has a load bar on there to indicate to users that data is loading this is fit to go live as it is.

I will close this issue for now, and then if you choose to develop this as part of phase 2 we can refer to it if needed. 

Thanks

Ella
