### ISSUE TITLE
Some map balloons lack links

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#58]
Some balloons on the map lack links to get to the initiative 

eg Amap des Hauts de Belleville in Paris

![paris](https://cloud.githubusercontent.com/assets/400875/19788291/5018ed30-9c9f-11e6-9501-5d1e7e2747fd.png)

**Comment by samuk** [comment]
Also searching for it finds the initiative, but the link goes to a Google doc?

http://transitionmovement.org/?s=+Amap+des+Hauts

**Comment by yvonnestruthers** [comment]
Hi Sam, 

Thanks for logging . 

@arhinostorm the 'Amap des Houts' one is a bit of an odd one, because when you click through on the list of initiatives (not by finding it in a search) it goes to the initiative, so there is a page for it: 

http://transitionmovement.org/transition-near-me/initiatives/amap-des-hauts-de-belleville/

I've had a further click through on the map, and most are working OK - these are the others I found that didn't have a 'view' on the map to click through to the initiative: 

Immenstadt im Wandel
USC en transicion
Two Peaks Trainsition
Samford Green Streets

These ones didn't have the google docs issue, but the read more link isn't clickable when you find them in the list eg http://transitionmovement.org/?s=Samford+

I had a quick look at the content of each of these in the CMS and I couldn't see an immediate pattern for why it is only happening for these ones... 

Please can you investigate? Thanks!

**Comment by arhinostorm** [comment]
Having looked the Amap des Hauts initiative it's excerpt contains markup. The is presumably from the importer. The excerpt field is supposed to be a short sentence containing only text (no markup) to describe the page.

This excerpts get used on the map popup and on pages where lots of initiatives are listed with a thumbnail, a link and a little bit of text. It gets limited in length if too short.

I changed the excerpt on the page (http://transitionmovement.org/wp-admin/post.php?post=3388&action=edit) to plain text (i.e. deleted all the markup) and that fixed the issue.

Essentially, you can't just have any old markup in excerpts. It needs to be plain text or you'll have issues.

**Comment by yvonnestruthers** [comment]
Thanks for the feedback Tom. I wondered whether this had anything to do with code in the excerpts, which we raised when we did the migration - this has come across from the old site. 

Sam - if you find issues like this again the first port of call will be to edit the excerpt of the initiative concerned to remove the HTML.

**Comment by samuk** [comment]
OK Thanks editing these now
