### ISSUE TITLE
Backup plugin 

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#70]
Hi Ella 

Could you let us know what you would charge to install this backup plugin

https://updraftplus.com/

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

Just repeating my comments via email: We actually implemented a back up plugin which is doing a daily back up pre go live (which currently saves to one of our Dropbox accounts) just for peace of mind as we weren't sure whether the hosts were doing it already and in the event that anything happened we wanted to ensure you could reach all your content again. 

So we wouldn't need to put a new plugin in place, however, we would need to change where the back up lives after go live - does Transition have a Dropbox account this could go to? The size of the daily back up is 4GB so capacity needs to be large enough to hold that.

Let me know how you'd like to proceed once you've discussed with Ainslie. 

Many thanks

Ella

**Comment by samuk** [comment]
Hi Ella

I was thinking of backing up to Google Drive if it's a service we already pay for, so we wouldn't have to pay for an additional Dropbox account.

It should be fairly trivial to install the plugin I think? So maybe we do that as the first job of the maintenance? If you're happy to keep the Dropbox one in place and updating to your account until then?

We do additionally have the 7 day daily backup via Hetzner, so it's belt and braces really.

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

Ok that sounds fine - I'm just checking with Tom if the plugin we have in place can backup to Google Drive as well as Dropbox. But as you say installing a new plugin would be relatively straightforward if needed and could be done as part of the maintenance. 

Happy to keep managing this via our Dropbox in the mean time, and I will update you on here once I have Tom's feedback re whether we can use the existing plugin with Google Drive or not. 

We would need the login details in order to get it set up in any event (whether with this plug in or another one) so could you provide those for me? 

Many thanks

Ella

**Comment by yvonnestruthers** [comment]
@arhinostorm just putting on here so everything is in the issue - is the plug in we are currently using able to back up to Google Drive? Or only Drop Box? 

Thanks!

**Comment by yvonnestruthers** [comment]
Google drive to use is: backups@transitionnetwork.org

(I will send the password seperately offline) 

Please either change the details of the backup plugin we are already using to use these Google Drive details, or, if the plug in we have in place can only use Dropbox, please recommend an alternative that is compatible with our version of WP and Google Drive. 

Please confirm which of the above you need to do. 

Thanks!

**Comment by yvonnestruthers** [comment]
Log in details not working currently - have requested new ones from Sam - will update again when new details received

**Comment by yvonnestruthers** [comment]
Update - we will need to use a different plug in to back up to Google Drive. Tom to recommend plug in to be used and set up. 

@arhinostorm please can you let me know how long you'll need to get this set up. This will come out of the maintenance time for December

**Comment by yvonnestruthers** [comment]
Tom has recommended that we use the following plug in to back up to google drive: 
https://updraftplus.com/support/configuring-google-drive-api-access-in-updraftplus/?utm_referrer=https%3A%2F%2Fwww.google.co.uk%2F]

He has tried to log in using the details provided to amend the settings in Google Drive in order to implement this but is getting the following error: You do not have sufficient permissions to view this page.

We need administrator access to the account to be able to get this set up. @samuk please could you change our permissions in order to give us the correct permissions to be able to change settings, and let me know once done please? 

I know you'll be busy preparing for go live today, so Monday/Tuesday is OK for this if you need more time.

**Comment by ainsliebeattie** [comment]
Sam is not at his desk today, so it will have to be monday.
cheers

Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb

**Comment by yvonnestruthers** [comment]
Hi @samuk are you ableto give me an update on when you will be able to change our permissions to allow us to change settings in Google Drive (please see my comment above for background)

Many thanks

**Comment by yvonnestruthers** [comment]
Update - Tom has got this working on the transitionmovement staging area - he will test this on the new area once the dev area is sorted with Hetzner

**Comment by yvonnestruthers** [comment]
Estimate: 15 minutes - I'll get this booked in with Tom

**Comment by arhinostorm** [comment]
Plugin setup to backup database and files once a day. The time at which it does this is random - in order to select the time (so say 2am when no one is using the site) you need to upgrade to the premium version of the plugin which is £54. 

15 mins.

**Comment by yvonnestruthers** [comment]
Hi @samuk @ainsliebeattie 

Please see above from Tom - please could you confirm if you will buy the premium version to avoid slowing the site at peak times when it is backing up. Or, if you are happy to stick with the free version that's in place and no further action required.  

Let me know if you'd like to upgrade. 

Many thanks
