### ISSUE TITLE
Install Rocket cache?

### ISSUE THREAD

**Issue by samuk** [transitionnetwork/TNv3.0#72]
Hi without caching we seem to have a page load of just over three seconds from the US.
https://tools.pingdom.com/#!/b0rjI/transitionmovement.org

Just under two from Stockholm
https://tools.pingdom.com/#!/tqEOu/http://transitionmovement.org

What would you charge to install the Rocket Cache plugin?
https://wp-rocket.me/features/
http://wpdevshed.com/best-wordpress-cache-plugin/

Thanks

Sam

**Comment by yvonnestruthers** [comment]
Hi Sam,

This is something we can do in the first month of maintenance post go live. So there wouldn't be an additional charge - the time taken would simply be deducted from the maintenance budget. 

I've created a new label for 'maintenance' items so that we can identify them as apart from work that's needing to happen before go live. 

Thanks

Ella

**Comment by ainsliebeattie** [comment]
hi all I have just paid for rocket and it asked that I download it...so I have added the zip file to the yoke and transition shared folder.  It didn't give me any account details so I am hoping you can get in. I am not working friday so if you need more information, you will ahve to call me on the mobile.

cheers
Ainslie

**Comment by ainsliebeattie** [comment]
Your pseudo (the email you used): 
ainsliebeattie@transitionnetwork.org

Your password has been automatically generated: 
()IYy*1lm8d7

**Comment by yvonnestruthers** [comment]
thanks Ainslie - I'll pass on the zip to Tom when he comes to work on this next week.

**Comment by yvonnestruthers** [comment]
Estimate: 15 minutes - I'll get this booked in with Tom

**Comment by arhinostorm** [comment]
Done. 15 mins.
