### ISSUE TITLE
Trainings Page

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#82]
Hi - URGENT - 

We still can't get into our Trainings page - this is uneditable and Wrong!  Can you please help urgently.
http://transitionmovement.org/do-transition/training/trainings/

**Comment by yvonnestruthers** [comment]
Hi Ainslie,

We spoke about this one on the phone some time ago - as I mentioned before, there are some 'pages' on the site which are custom post types (trainings is one of these). In Wordpress terms, these are not pages, but listings - so in this case, the trainings 'page' is simply a list of trainings, it is not a 'page' in the sense that you can edit it. 

If you need to change the wording in the hero then we can do that for you (please let me know what you'd like). Otherwise, this is just a listing repository so isn't editable. 

I'll close this issue for now, but let me know if you need the hero area wording changing and we can do that for you.

**Comment by ainsliebeattie** [comment]
hi Ella - - it is the related content that is really challenging - I
understand the listings are a challenge that we can't adjust, but it would
be good to understand how there is related content when we can't manage it.

Also I cannot see it as a page for people to find at it really needs to be
on the Training home page as a section for people to go to - so we are
trying to get it as a box / page...and we have finally decided to change
the name of it to Our Program

if that can all be done, that would be great.
A

Ainslie Beattie
Communications Coordinator
Transition Network
07478577752

www.transitionnetwork.org
@ainslieb
