### ISSUE TITLE
boxes where things don't fit...

### ISSUE THREAD

**Issue by ainsliebeattie** [transitionnetwork/TNv3.0#83]
Hi - I know I have raised at least one of these before....

They don't look good..  each one is cutting off text in strange spots...how do we cure it please?

cheers

<img width="817" alt="screen shot 2016-11-20 at 10 34 23 pm" src="https://cloud.githubusercontent.com/assets/22507393/20466786/96e73afc-af71-11e6-98b3-30841d53ae9f.png">
<img width="759" alt="screen shot 2016-11-20 at 10 34 11 pm" src="https://cloud.githubusercontent.com/assets/22507393/20466787/9859bdf6-af71-11e6-99c2-d30848e6b3e5.png">
<img width="1156" alt="screen shot 2016-11-20 at 10 07 06 pm" src="https://cloud.githubusercontent.com/assets/22507393/20466788/9a75535c-af71-11e6-8866-d3723d4f5902.png">

**Comment by yvonnestruthers** [comment]
Hi Ainslie,

With the initiatives one, it is because there is too much copy withing the box, so for that one it's going to be a case of editing the text down to be a similar amount to what you have in hubs. 

For the other two @arhinostorm please could you do the following: 

- Stories http://transitionmovement.org/stories/ - the above is happening when you reduce the size of the screen. Jay sugests to move the filters down into the white space below the hero

- Resources - please increase the height of the resources listings boxes to be tall enough to handle a 2 line title 

Thanks!

**Comment by yvonnestruthers** [comment]
I'm just closing this one to set these up as seperate issues to make it clearer
